#!/sbin/sh
# 
# /system/addon.d/70-gapps.sh
#
. /tmp/backuptool.functions

list_files() {
cat <<EOF
etc/g.prop
etc/permissions/com.google.android.media.effects.xml
etc/permissions/features.xml
etc/permissions/com.google.android.maps.xml
etc/permissions/com.google.widevine.software.drm.xml
etc/preferred-apps/google.xml
framework/com.google.widevine.software.drm.jar
framework/com.google.android.media.effects.jar
framework/com.google.android.maps.jar
vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N.bin
vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7
vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2.bin
vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32.bin
vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32.bin
vendor/pittpatt/models/detection/yaw_roll_face_detectors.6
vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24.bin
vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24.bin
vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24.bin
usr/srec/en-US/g2p_fst
usr/srec/en-US/wordlist
usr/srec/en-US/hotword_word_symbols
usr/srec/en-US/ep_acoustic_model
usr/srec/en-US/compile_grammar.config
usr/srec/en-US/hclg_shotword
usr/srec/en-US/endpointer_dictation.config
usr/srec/en-US/metadata
usr/srec/en-US/contacts.abnf
usr/srec/en-US/norm_fst
usr/srec/en-US/phone_state_map
usr/srec/en-US/hotword_normalizer
usr/srec/en-US/rescoring_lm
usr/srec/en-US/clg
usr/srec/en-US/dict
usr/srec/en-US/normalizer
usr/srec/en-US/hmmlist
usr/srec/en-US/google_hotword.config
usr/srec/en-US/grammar.config
usr/srec/en-US/offensive_word_normalizer
usr/srec/en-US/c_fst
usr/srec/en-US/dictation.config
usr/srec/en-US/dnn
usr/srec/en-US/hmm_symbols
usr/srec/en-US/endpointer_voicesearch.config
usr/srec/en-US/phonelist
usr/srec/en-US/classifier
usr/srec/config/en.us/dictionary/cmu6plus.ok.zip
usr/srec/config/en.us/dictionary/basic.ok
usr/srec/config/en.us/dictionary/enroll.ok
usr/srec/config/en.us/baseline.par
usr/srec/config/en.us/grammars/phone_type_choice.g2g
usr/srec/config/en.us/grammars/boolean.g2g
usr/srec/config/en.us/grammars/VoiceDialer.g2g
usr/srec/config/en.us/baseline8k.par
usr/srec/config/en.us/models/generic8_f.swimdl
usr/srec/config/en.us/models/generic.swiarb
usr/srec/config/en.us/models/generic11_f.swimdl
usr/srec/config/en.us/models/generic8_m.swimdl
usr/srec/config/en.us/models/generic11.lda
usr/srec/config/en.us/models/generic11_m.swimdl
usr/srec/config/en.us/models/generic8.lda
usr/srec/config/en.us/baseline11k.par
usr/srec/config/en.us/g2p/en-US-ttp.data
app/Vending.apk
app/Exchange2.apk
app/VoiceSearchStub.apk
app/GoogleOneTimeInitializer.apk
app/LatinImeDictionaryPack.apk
app/Calendar.apk
app/NetworkLocation.apk
app/GoogleFeedback.apk
app/Gmail.apk
app/GoogleBackupTransport.apk
app/OneTimeInitializer.apk
app/GoogleEars.apk
app/MediaUploader.apk
app/GoogleContactsSyncAdapter.apk
app/GooglePlus.apk
app/SetupWizard.apk
app/TalkBack.apk
app/Email.apk
app/GoogleTTS.apk
app/FaceLock.apk
app/QuickSearchBox.apk
app/GooglePartnerSetup.apk
app/ChromeBookmarksSyncAdapter.apk
app/Launcher2.apk
app/ConfigUpdater.apk
app/GoogleLoginService.apk
app/Hangouts.apk
app/Music.apk
app/VoiceDialer.apk
app/GoogleServicesFramework.apk
app/GoogleCalendarSyncAdapter.apk
app/GenieWidget.apk
app/YouTube.apk
app/GmsCore.apk
app/VideoEditor.apk
app/LatinIME.apk
tts/lang_pico/de-DE_ta.bin
tts/lang_pico/es-ES_zl0_sg.bin
tts/lang_pico/it-IT_cm0_sg.bin
tts/lang_pico/es-ES_ta.bin
tts/lang_pico/fr-FR_nk0_sg.bin
tts/lang_pico/de-DE_gl0_sg.bin
tts/lang_pico/fr-FR_ta.bin
tts/lang_pico/it-IT_ta.bin
lib/librs.antblur_constant.so
lib/librsjni.so
lib/libwebrtc_audio_coding.so
lib/libgtalk_stabilize.so
lib/libvcdecoder_jni.so
lib/libpatts_engine_jni_api.so
lib/libgoggles_clientvision.so
lib/librs.grey.so
lib/libAppDataSearch.so
lib/libgtalk_jni.so
lib/libfilterpack_facedetect.so
lib/libjni_t13n_shared_engine.so
lib/libspeexwrapper.so
lib/librs.film_base.so
lib/librs.antblur.so
lib/libplus_jni_v8.so
lib/libvorbisencoder.so
lib/librs.drama.so
lib/libwebp_android.so
lib/libgames_rtmp_jni.so
lib/libfrsdk.so
lib/librs.retrolux.so
lib/librs.antblur_drama.so
lib/librs.image_wrapper.so
lib/libRSSupport.so
lib/libgoogle_recognizer_jni_l.so
lib/librs.fixedframe.so
lib/libfacelock_jni.so
lib/libvideochat_jni.so
EOF
}

case "$1" in
  backup)
    list_files | while read FILE DUMMY; do
      backup_file $S/$FILE
    done
  ;;
  restore)
    list_files | while read FILE REPLACEMENT; do
      R=""
      [ -n "$REPLACEMENT" ] && R="$S/$REPLACEMENT"
      [ -f "$C/$S/$FILE" ] && restore_file $S/$FILE $R
    done
  ;;
  pre-backup)
    # Stub
  ;;
  post-backup)
    # Stub
  ;;
  pre-restore)
    # Stub
  ;;
  post-restore)
    # Stub
  ;;
esac
